---
- name: Install packages
  apt:
    update_cache: yes
    name: "{{ prerequisites_packages }}"
    force_apt_get: yes

- name: Update APT cache
  apt:
    upgrade: full
    update_cache: yes
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
    cache_valid_time: 86400

- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install Node 14
  command: nvm use 14