---
- name: Install packages
  apt:
    update_cache: yes
    name: "{{ prerequisites_packages }}"
    force_apt_get: yes

- name: Update APT cache
  apt:
    upgrade: full
    update_cache: yes
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
    cache_valid_time: 86400
