---
- hosts: all
  become: true

  vars_files:
    - encrypted/passwords.yml

  roles:
    - { name: base, tags: base }
    - { name: edimax-7612, tags: wlan }
    - { name: accesspoint, tags: accesspoint }
    - { name: deploy-test-scripts, tags: scripts }
    - { name: deploy-pondpi, tags: deploy }