---
- name: Install DNSmasq package
  apt:
    name: dnsmasq
    update_cache: yes
    state: latest

- name: Install template for DNSmasq
  template:
    src: "templates/dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dnsmasq

- name: Enable DNSmasq
  service:
    name: dnsmasq
    enabled: yes

- name: Start DNSmasq
  service:
    name: dnsmasq
    state: started
  register: dnsmasq_started